[build]
  command = "npm install && npm run build"
  functions = "functions"

[functions]
    included_files = ["./express/*.json", "./*.json"] 
    
[[redirects]]
  from = "/server/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
